### ISSUE TITLE
os_detect: OsNotDetected raised on Tizen OS

### ISSUE THREAD

**Issue by again4you** [ros-infrastructure/rospkg#126]
## Problem
I found out that OsNotDetected rose when running on Tizen OS as below.

```bash
# python os_detect.py
Traceback (most recent call last):
  File "os_detect.py", line 722, in <module>
    print("OS Name:     %s" % detect.get_name())
  File "os_detect.py", line 656, in get_name
    self.detect_os()
  File "os_detect.py", line 626, in detect_os
    raise OsNotDetected("Could not detect OS, tried %s" % attempted)
__main__.OsNotDetected: Could not detect OS, tried ['windows', 'ubuntu', 'slackware', 'rhel', 'qnx', 'osx', 'opensuse', 'opensuse', 'opensuse', 'neon', 'mint', 'linaro', 'gentoo', 'funtoo', 'freebsd', 'fedora', 'elementary', 'elementary', 'debian', 'cygwin', 'centos', 'manjaro', 'arch']
```

## Reason
The main and simple reason is that os_detect module does not support __Tizen__ OS.

**Comment by again4you** [comment]
I just submit PR #127 to resolve this issue.

### Test Result
```bash
# python os_detect.py
OS Name:     tizen
OS Version:  5.0.0
OS Codename: tizen5/unified
```

Tizen is a Linux based open operating system, which is officially registered at Linux Foundation. So I would be happy if Tizen is supported on os_detect module.

**Comment by again4you** [comment]
PR #127 is merged so this issue is closed!
